{
  "comments": [
    {
      "key": {
        "uuid": "40164286_de323c53",
        "filename": "src/mmpack-build/src_package.py",
        "patchSetId": 1
      },
      "lineNbr": 399,
      "author": {
        "id": 1017136
      },
      "writtenOn": "2020-01-08T14:53:57Z",
      "side": 1,
      "message": "this is already documented by the function raising the exception",
      "range": {
        "startLine": 398,
        "startChar": 0,
        "endLine": 399,
        "endChar": 76
      },
      "revId": "a9edb6691449656bba716cd7a36a368b7847b5ca",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}